### ISSUE TITLE
scala-reflection insists that all non-case constructor arguments be val (or presumably var)

### ISSUE THREAD

**Issue by DavidGoodenough** [gzoller/scala-reflection#17]
For no apparently good reason scala-reflection checks in or about (TastyReflection.scala:362) that all non-case constructor arguments must be val, which means that scala-reflection can not reflect all scala classes.  

While I can see this might be an issue for some uses of scala-reflection, why is it a restriction in scala-reflection and can it be lifted.

My particular use case is for superclasses where values are being passed through a class to its superclass (where it is a val) from a subclass.  It is thus never going to be used directly, as the constructor for the subclass passes the right thing in, but this restriction means I can not use scala-reflection to model my classes.  And yes I know that subclasssing is regarded with horror by some in the Scala community, but I have found no better way of achieving what is common place in the Java world.

**Comment by pjfanning** [comment]
in my fork, I'm looking at ignoring the non-val constructor params - https://github.com/pjfanning/scala3-reflection/pull/5

**Comment by gzoller** [comment]
Sorry for the delay…. I’ll have a look.  I seem to remember there’s a difference in visibility inside the compiler for non-val constructor fields.  They’re treated differently internally and basicaly I can’t see them (or I haven’t figured out how).  Your idea of an annotation to completely exclude a class from reflection processing is a goid one, though, and should be straightforward to do.
