### ISSUE TITLE
v1.0.0 release jar seems to have some classes that do not support running on Java 8 runtime

### ISSUE THREAD

**Issue by pjfanning** [gzoller/scala-reflection#18]
Thanks for the great project. I've been trying it out with jackson-module-scala.

I got the error below when running some unit tests with Java 8 (but not with Java 17).

Would it be possible to republish your jar but built with Java 8 for better compatibility? 

I did run your build with Java 8 and ran into issues with munit which seems to require Java 11 (class file version 55.0). An upgrade of munit solved this. - see https://github.com/gzoller/scala-reflection/pull/19

```
[error] java.lang.UnsupportedClassVersionError: co/blocke/scala_reflection/S3Reflection has been compiled by a more recent version of the Java Runtime (class file version 57.0), this version of the Java Runtime only recognizes class file versions up to 52.0
[error] 	at java.lang.ClassLoader.defineClass1(Native Method)
[error] 	at java.lang.ClassLoader.defineClass(ClassLoader.java:757)
[error] 	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
[error] 	at java.net.URLClassLoader.defineClass(URLClassLoader.java:468)
[error] 	at java.net.URLClassLoader.access$100(URLClassLoader.java:74)
[error] 	at java.net.URLClassLoader$1.run(URLClassLoader.java:369)
[error] 	at java.net.URLClassLoader$1.run(URLClassLoader.java:363)
[error] 	at java.security.AccessController.doPrivileged(Native Method)
[error] 	at java.net.URLClassLoader.findClass(URLClassLoader.java:362)
[error] 	at sbt.internal.ManagedClassLoader.findClass(ManagedClassLoader.java:102)
[error] 	at java.lang.ClassLoader.loadClass(ClassLoader.java:419)
[error] 	at java.lang.ClassLoader.loadClass(ClassLoader.java:352)
[error] 	at co.blocke.scala_reflection.RTypeOfNoPlugin$$anon$1.applyOrElse(RType.scala:181)
[error] 	at co.blocke.scala_reflection.RTypeOfNoPlugin$$anon$1.applyOrElse(RType.scala:180)
[error] 	at scala.collection.IterableOnceOps.collectFirst(IterableOnce.scala:1079)
[error] 	at scala.collection.IterableOnceOps.collectFirst$(IterableOnce.scala:1071)
[error] 	at scala.collection.AbstractIterable.collectFirst(Iterable.scala:919)
[error] 	at co.blocke.scala_reflection.RTypeOfNoPlugin.of$$anonfun$1(RType.scala:181)
[error] 	at scala.collection.mutable.HashMap.getOrElse(HashMap.scala:436)
[error] 	at co.blocke.scala_reflection.RTypeOfNoPlugin.of(RType.scala:84)
```

**Comment by gzoller** [comment]
Yeah, I needed to pick a JVM for the built artifacts, and Java 8 is, well…pretty old.  There have been security updates to the jvm since then and many enterprises won’t want to run such an old jvm, so I picked 13, which was the oldest my employer at the time would run.

**Comment by pjfanning** [comment]
@gzoller Java 8 is still supported under LTS and even Scala generates Java 8 format classes. Java 11 is another LTS release. Would it be possible to reconsider your decision not to consider this issue?

**Comment by pjfanning** [comment]
@gzoller just for some background: while you were way, I was using scala-reflection (great project btw) and forked it to get it working for my use case. I have some details on the readme of https://github.com/pjfanning/scala3-reflection. If you are interested, you could look at the commits I've made too. It would be my preference to not maintain my fork and if you are amenable, I could submit the changes to your project.

**Comment by pjfanning** [comment]
@gzoller v1.1.0 is also published to only work with Java 13 and above
