### ISSUE TITLE
ClassInfo.infoClass call fails with ClassNotFoundException for class defined inside an Object

### ISSUE THREAD

**Issue by pjfanning** [gzoller/scala-reflection#20]
https://github.com/pjfanning/scala-reflection/commit/cd1b47d0a0daa73dfbdde73add5d4e44d76ec1ba

The class name that is derived for the ScalaCaseClassInfo appears to be wrong and when `.infoClass` is called, the class is not found.

The existing scala-reflection code thinks the class name is TestObject$.GenericTestClass when TestObject$GenericTestClass seems to be correct - note the dot after dollar (in the initial name).

Alternatively, the infoClass function could adjust the class name before calling Class.forName.

**Comment by gzoller** [comment]
That’s interesting.  I’ll check it out.

**Comment by gzoller** [comment]
Yep, it was a bug.  Fixed in next release.
