### ISSUE TITLE
Comparison with izumi-reflect?

### ISSUE THREAD

**Issue by pshirshov** [gzoller/scala-reflection#23]
Hi,

I'm wondering if you may add some notes about the differences between this library and https://github.com/zio/izumi-reflect

**Comment by gzoller** [comment]
I’m not familiarvwith this library, unfortunately.  It doesn’t appear to be native to Scala 3, although a port is mentioned.  Not sure if they use macros or not—if not I’d be very curious how it performs.  Try it out and see what the reflected data structures give you in both.
