### ISSUE TITLE
Scala.js compatibility

### ISSUE THREAD

**Issue by simlei** [gzoller/scala-reflection#43]
Hi, could you clarify whether the compiler plugin could prevent this library from being used in a scala.js project? And whether using the (slower) no-plugin approach would work or not, either? Thanks!

**Comment by gzoller** [comment]
I'm afraid I can't honestly say... I don't know much at all about scala.js.  Try it, would be my advice, however don't hold out too much hope.  The compiler plugin analyzes classes as they're compiled and creates a bundle of information (RType) holding what it learned.  It stuffs a serialized RType blob into an Annotation attached to the class, so "reflection" looks for this annotation and deserializes the blob, and presto--you have deep info about your class.  

Does scala.js have annotations?  Assuming that the code goes thru the same scala compiler as "normal" scala, generating the RType should be the same.  Only the last bit--where to put the RType info would be different.

I'll leave this issue open for now.

**Comment by gzoller** [comment]
Hi, simlie... I'm working to release 1.2.0, which has experimental scala.js support.  Basically, you can do:
```val foo = RType.ofJS[MyClass]```.  This returns a String containing basically an RType in JSON form.  You should be able to parse and interrogate the object in scala.js.

Give it a try and let me know how it works for you.
