### ISSUE TITLE
Does not work with SBT Assembly

### ISSUE THREAD

**Issue by AlanBurlison** [gzoller/scala-reflection#63]
Scala3, scala-reflection 1.20 fails with 100s of errors similar to this:

```[error] 193 error(s) were encountered during the merge:
[error] java.lang.RuntimeException: 
[error] Deduplicate found different file contents in the following:
[error]   Jar name = scala-reflection_3-1.2.0.jar, jar org = co.blocke, entry target = co/blocke/scala_reflection/info/AliasInfo.tasty
[error]   Jar name = scala3-reflection_3-1.2.0.jar, jar org = com.github.pjfanning, entry target = co/blocke/scala_reflection/info/AliasInfo.tasty
[error] Deduplicate found different file contents in the following:
[error]   Jar name = scala-reflection_3-1.2.0.jar, jar org = co.blocke, entry target = co/blocke/scala_reflection/info/JavaFieldInfo.class
[error]   Jar name = scala3-reflection_3-1.2.0.jar, jar org = com.github.pjfanning, entry target = co/blocke/scala_reflection/info/JavaFieldInfo.class
[error] Deduplicate found different file contents in the following:
[error]   Jar name = scala-reflection_3-1.2.0.jar, jar org = co.blocke, entry target = co/blocke/scala_reflection/impl/StringByteEngine.tasty
[error]   Jar name = scala3-reflection_3-1.2.0.jar, jar org = com.github.pjfanning, entry target = co/blocke/scala_reflection/impl/StringByteEngine.tasty
[error] Deduplicate found different file contents in the following:
[error]   Jar name = scala-reflection_3-1.2.0.jar, jar org = co.blocke, entry target = co/blocke/scala_reflection/impl/NonCaseClassReflection.class
[error]   Jar name = scala3-reflection_3-1.2.0.jar, jar org = com.github.pjfanning, entry target = co/blocke/scala_reflection/impl/NonCaseClassReflection.class
[error] Deduplicate found different file contents in the following:
[error]   Jar name = scala-reflection_3-1.2.0.jar, jar org = co.blocke, entry target = co/blocke/scala_reflection/info/EitherInfo.class
[error]   Jar name = scala3-reflection_3-1.2.0.jar, jar org = com.github.pjfanning, entry target = co/blocke/scala_reflection/info/EitherInfo.class
```

**Comment by pjfanning** [comment]
You will need to use one of the 2 jars - you can't use both.

Try excluding com.github.pjfanning:scala3-reflection

https://www.scala-sbt.org/1.x/docs/Library-Management.html#Exclude+Transitive+Dependencies

**Comment by AlanBurlison** [comment]
Thanks for the quick reply, but if my app is scala3 shouldn't I be excluding `com.github.pjfanning:scala-reflection`?

I'm also not sure why both are being pulled in in the first place, I have this in `build.sbt`:

```
  "co.blocke"                      %% "scala-reflection"                     % "1.2.0",
```

**Comment by AlanBurlison** [comment]
I'm following https://github.com/pjfanning/jackson-scala3-reflection-extensions which references https://github.com/gzoller/scala-reflection, hence the `co.blocke.scala-reflection` inclusion, but that seems to conflict. I've removed it, but then I get errors like this:

```[error] Deduplicate found different file contents in the following:
[error]   Jar name = scala3-reflection_3-1.2.0.jar, jar org = com.github.pjfanning, entry target = scala/tasty/inspector/Inspector.tasty
[error]   Jar name = scala3-tasty-inspector_3-3.2.0.jar, jar org = org.scala-lang, entry target = scala/tasty/inspector/Inspector.tasty```

Which looks like a conflict between your library and a standard Scala one?

**Comment by pjfanning** [comment]
I don't have much time over the next week or 2 to look into any of this.
* jackson-scala3-reflection-extensions is at best an experimental lib with little to no adoption
  * you can probably remove it and just work around any of the issues it might be solving for you
* it might be possible to exclude scala.tasty.inspector.Inspector from scala3-reflection (which is basically a copy of co.blocke:scala-reflection with a couple of small mods - but both jars have this class) 
* it is also probably possible to get sbt-assembly to take 1 copy of the duplicate class and not to fail

@gzoller any ideas why scala.tasty.inspector.Inspector is in the scala-reflection jar and if it is needed?

**Comment by AlanBurlison** [comment]
Thanks for the suggestions, I'll try them out and let you know.

**Comment by AlanBurlison** [comment]
> Jackson-scala3-reflection-extensions is at best an experimental lib with little to no adoption you can probably remove it and just work around any of the issues it might be solving for you

Hmm, if I remove it I get:

```[error] (Compile / compileIncremental) java.lang.ClassCastException: class dotty.tools.dotc.core.Symbols$NoSymbol$ cannot be cast to class dotty.tools.dotc.core.Symbols$ClassSymbol (dotty.tools.dotc.core.Symbols$NoSymbol$ and dotty.tools.dotc.core.Symbols$ClassSymbol are in unnamed module of loader sbt.internal.classpath.ClassLoaderCache$Key$CachedClassLoader @3d608cba)
[error] Total time: 10 s, completed 31 May 2023, 12:37:13
```
If I add back the dependency on `co.blocke" %% "scala-reflection" % "1.2.0",` *or* disable `addCompilerPlugin("com.github.pjfanning" %% "scala3-reflection" % "1.2.0")` then the problem above and the  `scala-reflection_3-1.2.0.jar` / `scala3-reflection_3-1.2.0.jar` conflict goes away, however the `Inspector.class` issue remains.

If I disable both the compiler plugin *and* disable the `co.blocke` dependency then I get a clean `assembly` run. I'm not clear why the compiler plugin is causing an issue, but as I understand it, it's a performance optimisation so I can likely live without it for now.

**Comment by pjfanning** [comment]
That scala.tasty.inspector.Inspector code is copied into scala-reflection/scala3-reflection - see https://github.com/gzoller/scala-reflection/blob/main/src/main/scala/co.blocke.scala_reflection/scala.tasty.inspector/Inspector.scala#L4-L8

**Comment by pjfanning** [comment]
based on https://users.scala-lang.org/t/compiler-plugins-and-dependencies/4765/5 and some experimentation I've done - it looks like the existing solution of copying the class into scala-reflection/scala3-reflection is the only viable solution.

Most users won't even notice the fact that scala.tasty.inspector.Inspector will appear in this jar and also in scala3-tasty-inspector. I'm afraid that sbt-assembly users (and users of similar tools that police against duplicate classes) will need to find some way to get their tool to ignore the duplication and just to choose 1 instance (preferably the scala3-tasty-inspector one).

**Comment by pjfanning** [comment]
I just reported an issue to the sbt team - https://github.com/sbt/sbt/issues/7269

**Comment by AlanBurlison** [comment]
Following your helpful hints (thanks!) I've ended up with this, which seems to work

```
autoCompilerPlugins := true
addCompilerPlugin("com.github.pjfanning" %% "scala3-reflection" % "1.2.0")
```

```
  "com.fasterxml.jackson.datatype" %  "jackson-datatype-jsr310"              % "2.15.1",
  "com.fasterxml.jackson.module"   %% "jackson-module-scala"                 % "2.15.1",
  "com.github.pjfanning"           %% "jackson-module-scala3-enum"           % "2.15.0",
  "co.blocke"                      %% "scala-reflection"                     % "1.2.0",
```

```
assembly / assemblyMergeStrategy := { file =>
  val inspector = """.*\bInspector\.(?:class|tasty)$""".r
  file match {
    case inspector() => MergeStrategy.last
    case o => (assembly / assemblyMergeStrategy).value(o)
  }
}
```

I checked the classpath SBT was using, `scala3-tasty-inspector` comes later in it so `last` seemed to be the right choice to follow your advice above.  And with debug enabled, it looks like the`assembly` plugin lists the conflics in classpath order:

```
[debug] Merge Strategy Used: Last
[debug] Resulting entries:
[debug]   Jar entry = scala/tasty/inspector/Inspector.tasty
[debug] Merge origins:
[debug]   Jar name = scala-reflection_3-1.2.0.jar, jar org = co.blocke, entry target = scala/tasty/inspector/Inspector.tasty
[debug]   Jar name = scala3-tasty-inspector_3-3.2.1.jar, jar org = org.scala-lang, entry target = scala/tasty/inspector/Inspector.tasty
[debug] 
[debug] Merge Strategy Used: Last
[debug] Resulting entries:
[debug]   Jar entry = scala/tasty/inspector/Inspector.class
[debug] Merge origins:
[debug]   Jar name = scala-reflection_3-1.2.0.jar, jar org = co.blocke, entry target = scala/tasty/inspector/Inspector.class
[debug]   Jar name = scala3-tasty-inspector_3-3.2.1.jar, jar org = org.scala-lang, entry target = scala/tasty/inspector/Inspector.class
```

This seems like an adequate and easy workaround until the SBT issue you logged is addressed.

**Comment by pjfanning** [comment]
@AlanBurlison please do not use both co.blocke:scala-reflection and com.github.pjfanning:scala3-reflection - use one or other but not both

**Comment by AlanBurlison** [comment]
If I remove `co.blocke:scala-reflection` I get this error:

```java.lang.ClassCastException: class dotty.tools.dotc.core.Symbols$NoSymbol$ cannot be cast to class dotty.tools.dotc.core.Symbols$ClassSymbol (dotty.tools.dotc.core.Symbols$NoSymbol$ and dotty.tools.dotc.core.Symbols$ClassSymbol are in unnamed module of loader sbt.internal.classpath.ClassLoaderCache$Key$CachedClassLoader @260f20bd) while running reflectionWorker on XXX/Main.scala```

**Comment by pjfanning** [comment]
so then don't use com.github.pjfanning:scala3-reflection - use just one of the 2 jars

**Comment by gzoller** [comment]
Seems resolved(?).  Thank you!
The next version (2.x series) will no longer require a compiler plugin nor use Tasty Inspector, so perhaps that will also help!
