### ISSUE TITLE
How to get the value of a field in a case class isn't documented

### ISSUE THREAD

**Issue by DavidPerezIngeniero** [gzoller/scala-reflection#94]
I've tried to browse the source code, and don't know how to get in runtime by relfection, the value of a field of given name of an instance of a case class.

Related stackoverflow question:
https://stackoverflow.com/questions/78833225/how-to-get-the-value-of-a-field-of-a-case-class-by-reflection-in-scala-3

**Comment by pjfanning** [comment]
Reflection is for accessing the metadata of Classes (field names, function names, etc). It is not for getting the data of class instances.
